### ISSUE TITLE
关于中文标题和多抓标题的问题

### ISSUE THREAD

**Issue by chunhuajiang** [sk1418/ghtoc#1]
Hi，

非常感谢你的工具，有两个问题，希望能得到解决：
- 中文标题。其实github能识别中文标题的，例如我的这篇文章：`https://github.com/tidyjiang8/zephyr-os-tips/blob/master/src/introduce/introduction.md`
- 多抓取了标题。当markdown中包含代码时，如果代码中包含 `#define`, `#ifdef`等相关预处理关键字时，会被错误地当成标题。

Thanks!

**Comment by sk1418** [comment]
謝謝你測試並發現問題, 我目前在休假期間, 不能保證時間來看這個, 但我儘量看看. 感覺不是什麼耗時的問題.

**Comment by chunhuajiang** [comment]
Thanks.

**Comment by sk1418** [comment]
利用饭前时间做了一些修改, 用你链接的那个文档实验了下好像可以, 但是没做太多测试. 我记得以前直接写中文github是不认的.

push到了dev branch, 请你测试一下, 如果有时间, 请特别测试下如果md里的`# .....` 标题含有特殊字符的,会不会有问题, 我猜可能会有 :-)  

现在代码段里的#应该不会被检测了.

总之你测试下吧, 如果有兴趣也可以帮着fix 

谢谢你哈

**Comment by chunhuajiang** [comment]
我特意做了下测试，测试文章的源码如下：

https://raw.githubusercontent.com/tidyjiang8/ghtoc/master/test/test2.md

预览后的网页如下：

https://github.com/tidyjiang8/ghtoc/blob/master/test/test2.md

测试结果如下：
- 中文测试失败。生成的目录为： `- [中文测试](#)`
- 代码中的`#`测试失败。生成了目录：`- [define](#define)`

另外，关于标题中的特殊符号，需要进行一些转换，你已经完成的功能包括：
- 空格转换为`-`
- 大写字母转换为小写字母

被错误转换的包括：
- 英文状态下的下划线`_`被省略掉了，而实际上不应该被省略

> 查看特殊符号是否需要转换、如何转换的方法：
> 
> 将鼠标移动到正文中的标题处，会在标题处的最左边出现两个小圆圈
> 
> 鼠标点击小圆圈，网页会在页内进行跳转，此时看地址栏，你会发现地址最后的符号变了
> 
> 对比网页中的标题与地址栏中最后面的符号

等你有空的时候改吧~

我的 python 属于小学生水平，只能看懂简单的程序，不能 fix 这些 bug。

**Comment by sk1418** [comment]
谢谢你这么详细测试..
中文我拿你那个网页实验倒是显示出来了(在md源码里)... 不知怎么搞的. 在国内休假又赶上过节, 心浮气躁地好歹修改了下, 不好意思... 等我有时间了仔细看看..

谢谢你.. 祝你中秋愉快.
BTW, 你是测试的dev  分支是吧?

**Comment by chunhuajiang** [comment]
Sorry. 之前没看你的 commit，直接拿了 master 分支测试的。刚刚拿 dev 分支测试了一下，中文问题解决了。

研究了一下你的代码，基本上弄明白了。你这样修改过后引入了新的问题：
- 有一些符号依然需要被省略，包括用英文输入的`~!@#$%^&*()+\`={}|:"<>?` 以及这些符号对应的在中文状态下的输入

　　==>我没想到比较好的解决办法
- 大写字母依然应该转为小写

　　==> 像你之前的那样，用 txt.lower（） 替换 txt

中秋快乐~

**Comment by oit63** [comment]
dev 版本很给力，感谢你的脚本！
顺便吐槽一下为什么Github 没有 TOC

**Comment by sk1418** [comment]
我都忘了是不是merge到 master了, 有空我看看
